### ISSUE TITLE
[Improvement] Chunk System

### ISSUE THREAD

**Issue by nonunknown** [thiagobruno/godot_TBP_GrassPath2D#4]
Have to say this plugin is awesome.

**Problem**
Low fps Issues with low-end machines

**Solution proposal** 
Maybe adding a chunk system ,  for example, stoping out-of-screen grass with visibilitynotifier, and group by chunks which one will interact and not.

**Comment by thrbr84** [comment]
@nonunknown thank you very much for the suggestion, I will do some tests with the VisibilityNotifier, I don't know if we will have a performance increase because I already used it at the beginning.

All "leafs" have the "Physics Process" disabled, even those that are visible on the screen, they are activated only when there is an interaction, and even so within the "maxProcess" defined as a parameter, for example: if the "maxProcess" is equal to 3 .. only 3 "leafs" will have "physics_process" activated while there is interaction, and after the interaction is over they will go back off.

**Comment by nonunknown** [comment]
interesting, didnt know that! , Also I will do test on 3d enviroments, using a 2d in 3d technique and share results

**Comment by thrbr84** [comment]
Cool, I'm curious about the results! Thanks

**Comment by thrbr84** [comment]
Improvements will be available on the next version
